# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Naser Al Madi, PhD"
description:	       "Blog"
details:             "My name is Naser Al Madi, and I am an Assistant Professor of Computer Science. Welcome to my blog on software engineering, academia, and research. This is a writing exercise more than anything, but I hope that you will find some of my rants useful."
author:              "Naser Al Madi"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
